// @ts-check
/**
 * Tests: the bundled HVAC icon set (DUCT-PLAN.md unit D16).
 *
 * - icons-custom.js ships the five M-sheet symbols (Supply Diffuser, Return
 *   Grille, RTU, VAV Box, Fire/Smoke Damper) under set 'hvac' — generated by
 *   scripts/build-hvac-symbols.js into my-counters/hvac/ and folded in by
 *   build:icons. A counter created with each one renders its sidebar swatch
 *   SVG with that path, with no console errors.
 * - The custom icon grids group the set under an "HVAC" heading: the Create
 *   tab's #counterIconGridCustom, the Quick Count grid (HVAC trade first) and
 *   the details modal's grid; the five cells sit contiguous under it.
 * - CFM → diffuser default: a Create-tab counter with a CFM and no icon click
 *   takes the Supply Diffuser (the selection moves live as the CFM is typed and
 *   restores the prefill when cleared); without a CFM the T2-05 prefill icon is
 *   unchanged; an explicit pick + CFM keeps the pick. Quick Count: a CFM'd
 *   type without a trade symbol (Thermostat-less plumbing "Tee") takes the
 *   diffuser; an HVAC type with its own symbol ("Return Grille") keeps it.
 * - render-pixels.spec.js (run alongside) proves the baselines are
 *   byte-identical — its fixture uses only pre-existing icons.
 */
const { test, expect } = require('@playwright/test');

// D19: the CFM / Mount height / Flex drop fields now fold under the
// "More ▸ air & mounting" disclosure on the Counter modal, which starts CLOSED
// on a trade-less (plumbing-default) project like these fixtures. Unfold it
// before touching them — the same click the estimator makes.
const unfoldAirMore = (page, which) => page.evaluate((w) => {
  const id = w === 'quick' ? 'counterQuickCountAirMore' : 'counterAirMore';
  const fields = document.getElementById(id + 'Fields');
  if (fields && fields.hidden) document.getElementById(id + 'Toggle').click();
}, which);

const path = require('path');

// In my-counters/hvac/ filename order (build:icons sorts each set by file).
const HVAC_NAMES = ['Fire/Smoke Damper', 'Return Grille', 'RTU', 'Supply Diffuser', 'VAV Box'];
const diffuserOf = (icons) => icons.find((i) => i.name === 'Supply Diffuser').value;

async function boot(page, errors) {
  page.on('console', (m) => {
    if (m.type() === 'error' && !(m.location()?.url || '').includes('config.local.js')) errors.push(m.text());
  });
  page.on('pageerror', (e) => errors.push(e.message));
  await page.goto('/app/');
  await page.waitForLoadState('networkidle');
  await page.locator('#pdfInput').setInputFiles(path.join(__dirname, 'test-2pages.pdf'));
  await page.waitForSelector('#pagesList .sidebar-item', { timeout: 10000 });
  await page.evaluate(() => { try { localStorage.removeItem('plumbingModifiers'); } catch (_) {} });
}
async function openCreateTab(page) {
  await page.evaluate(() => document.getElementById('addCounter')?.click());
  await page.waitForSelector('#counterModal.visible', { timeout: 5000 });
  await expect(page.locator('#counterCreatePanel')).toBeVisible();
  await unfoldAirMore(page);
}
async function openQuickTab(page) {
  await page.evaluate(() => { window.App.showModal('counterModal'); window.App.showCounterTab('quickcount'); });
  await page.waitForSelector('#counterModal.visible', { timeout: 5000 });
  await expect(page.locator('#counterQuickCountPanel')).toBeVisible();
  await unfoldAirMore(page, 'quick');
}
const hvacIcons = (page) => page.evaluate(() => window.App.getEffectiveCustomIcons().filter((ic) => ic.set === 'hvac').map((ic) => ({ name: ic.name, value: ic.value, viewBox: ic.viewBox })));
const lastCounter = (page) => page.evaluate(() => { const c = window.state.counters[window.state.counters.length - 1]; return { name: c.name, icon: c.icon, cfm: 'cfm' in c ? c.cfm : undefined }; });
const iconNameOf = (page, value) => page.evaluate((v) => window.App.getIconName(v), value);

test.describe('HVAC icon set (D16)', () => {
  /** @type {string[]} */
  let errors;
  test.beforeEach(async ({ page }) => { errors = []; await boot(page, errors); });

  test('icons-custom.js ships the five symbols under set hvac; each renders as a sidebar swatch', async ({ page }) => {
    const icons = await hvacIcons(page);
    expect(icons.map((i) => i.name)).toEqual(HVAC_NAMES);
    for (const ic of icons) expect(ic.viewBox).toBe('0 0 1200 1200');
    expect(await page.evaluate(() => typeof window.App.cfmDefaultIcon)).toBe('function');
    expect(await page.evaluate(() => window.App.cfmDefaultIcon())).toBe(diffuserOf(icons));

    for (const ic of icons) {
      await openCreateTab(page);
      await page.locator('#counterCreatePanel .counter-icon-tab[data-icon-tab="custom"]').click();
      const cell = page.locator('#counterIconGridCustom .icon-cell[data-path="' + ic.value + '"]');
      await expect(cell).toHaveCount(1);
      await cell.click();
      await expect(cell).toHaveClass(/selected/);
      await page.locator('#counterName').fill('');   // blank name → the icon's name
      await page.locator('#counterCreate').click();
      await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
      const c = await lastCounter(page);
      expect(c).toEqual({ name: ic.name, icon: ic.value, cfm: undefined });
      // The sidebar row draws the swatch SVG with that exact path.
      const swatch = page.locator('#countersList .sidebar-item').last().locator('.counter-drag-handle svg path');
      await expect(swatch).toHaveAttribute('d', ic.value);
      expect(await page.locator('#countersList .sidebar-item').last().locator('svg').getAttribute('viewBox')).toBe('0 0 1200 1200');
    }
    expect(await page.evaluate(() => window.state.counters.length)).toBe(5);
    expect(errors).toEqual([]);
  });

  test('the custom icon grids show an HVAC group with the five cells together (Create tab, Quick Count, details)', async ({ page }) => {
    const icons = await hvacIcons(page);
    const values = icons.map((i) => i.value);
    // Walks a grid: the HVAC heading exists and the next five data-path cells after it are exactly the set.
    const groupUnderHeading = (sel) => page.evaluate(({ sel, n }) => {
      const grid = document.querySelector(sel);
      const kids = Array.from(grid.children);
      const h = kids.findIndex((k) => k.classList.contains('icon-grid-heading') && k.textContent === 'HVAC');
      if (h < 0) return { headings: kids.filter((k) => k.classList.contains('icon-grid-heading')).map((k) => k.textContent), cells: null };
      const cells = [];
      for (let i = h + 1; i < kids.length && cells.length < n; i++) {
        if (kids[i].classList.contains('icon-grid-heading')) break;
        if (kids[i].dataset.path) cells.push(kids[i].dataset.path);
      }
      return { headings: kids.filter((k) => k.classList.contains('icon-grid-heading')).map((k) => k.textContent), cells };
    }, { sel, n: values.length });

    await openCreateTab(page);
    const create = await groupUnderHeading('#counterIconGridCustom');
    expect(create.headings).toEqual(expect.arrayContaining(['Plumbing', 'Electrical', 'HVAC']));
    expect(create.cells).toEqual(values);

    // Quick Count on the HVAC trade: the HVAC set leads the grid.
    await openQuickTab(page);
    await page.click('#counterQuickCountTradeSegment [data-trade="hvac"]');
    expect(await page.evaluate(() => window.state.trade)).toBe('hvac');
    const quick = await groupUnderHeading('#counterQuickCountIconGridCustom');
    expect(quick.headings[0]).toBe('HVAC');
    expect(quick.cells).toEqual(values);
    // The HVAC profile's types pre-select their symbol (constants.js HVAC_DEFAULTS.iconNameByType).
    for (const [type, name] of [['Supply Diffuser', 'Supply Diffuser'], ['Return Grille', 'Return Grille'], ['Exhaust Grille', 'Return Grille'], ['VAV Box', 'VAV Box'], ['RTU', 'RTU'], ['Damper', 'Fire/Smoke Damper']]) {
      await page.selectOption('#counterQuickCountType', type);
      const sel = await page.evaluate(() => document.querySelector('#counterQuickCountIconGridCustom .icon-cell.selected')?.getAttribute('data-path'));
      expect(await iconNameOf(page, sel)).toBe(name);
    }
    await page.click('#counterQuickCountCancel');

    // The details modal's grid carries the heading too.
    await openCreateTab(page);
    await page.locator('#counterCreate').click();
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    await page.evaluate(() => window.App.openCounterLineTypeDetailsModal('counter', window.state.counters[0]));
    await page.waitForSelector('#counterLineTypeDetailsModal.visible', { timeout: 5000 });
    const details = await groupUnderHeading('#counterLineTypeDetailsIconGridCustom');
    expect(details.cells).toEqual(values);
    expect(errors).toEqual([]);
  });

  test('Create tab: a CFM with no icon pick takes the Supply Diffuser; no CFM keeps the prefill; a pick wins', async ({ page }) => {
    const diffuser = diffuserOf(await hvacIcons(page));

    // 1. No CFM → the T2-05 prefill (the first unused ordered icon), no cfm key.
    await openCreateTab(page);
    const prefill = await page.evaluate(() => document.querySelector('#counterIconGrid .icon-cell.selected')?.getAttribute('data-path'));
    expect(prefill).toBe(await page.evaluate(() => window.App.getOrderedIcons()[0].value));
    await page.locator('#counterCreate').click();
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect(await lastCounter(page)).toEqual({ name: await iconNameOf(page, prefill), icon: prefill, cfm: undefined });

    // 2. CFM typed, no click → the selection moves to the diffuser live, and Create stamps it.
    await openCreateTab(page);
    await page.locator('#counterName').fill('SD-1');
    await page.locator('#counterCfm').fill('250');
    const selectedAfterCfm = await page.evaluate(() => document.querySelector('#counterModal .icon-cell.selected')?.getAttribute('data-path'));
    expect(selectedAfterCfm).toBe(diffuser);
    // Clearing the CFM restores the prefill selection.
    await page.locator('#counterCfm').fill('');
    expect(await page.evaluate(() => document.querySelector('#counterModal .icon-cell.selected')?.getAttribute('data-path'))).not.toBe(diffuser);
    await page.locator('#counterCfm').fill('250');
    await page.locator('#counterCreate').click();
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect(await lastCounter(page)).toEqual({ name: 'SD-1', icon: diffuser, cfm: 250 });

    // 3. An explicit pick + CFM keeps the pick (a plumbing built-in here).
    await openCreateTab(page);
    const pick = await page.evaluate(() => window.App.getOrderedIcons()[3].value);
    await page.locator('#counterIconGrid .icon-cell[data-path="' + pick + '"]').click();
    await page.locator('#counterName').fill('Picked 100');
    await page.locator('#counterCfm').fill('100');
    expect(await page.evaluate(() => document.querySelector('#counterModal .icon-cell.selected')?.getAttribute('data-path'))).toBe(pick);
    await page.locator('#counterCreate').click();
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect(await lastCounter(page)).toEqual({ name: 'Picked 100', icon: pick, cfm: 100 });

    // 4. The picked state never leaks into the next create: a fresh panel with a CFM → diffuser again.
    await openCreateTab(page);
    await page.locator('#counterName').fill('SD-2');
    await page.locator('#counterCfm').fill('300');
    await page.locator('#counterCreate').click();
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect(await lastCounter(page)).toEqual({ name: 'SD-2', icon: diffuser, cfm: 300 });

    // 5. An SVG upload after the CFM is an explicit pick too: the uploaded icon wins over the default.
    await openCreateTab(page);
    await page.locator('#counterName').fill('Uploaded 120');
    await page.locator('#counterCfm').fill('120');
    const before = await page.evaluate(() => window.App.getUserCustomIcons().length);
    await page.locator('#customIconUploadInput').setInputFiles({
      name: 'my-diffuser.svg', mimeType: 'image/svg+xml',
      buffer: Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect x="4" y="4" width="24" height="24"/></svg>'),
    });
    await page.waitForFunction((n) => window.App.getUserCustomIcons().length === n + 1, before, { timeout: 5000 });
    const uploaded = await page.evaluate(() => { const u = window.App.getUserCustomIcons(); return u[u.length - 1].value; });
    await page.locator('#counterCreate').click();
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect(await lastCounter(page)).toEqual({ name: 'Uploaded 120', icon: uploaded, cfm: 120 });
    expect(errors).toEqual([]);
  });

  test('Quick Count: a CFM with no pick and no type symbol takes the diffuser; a trade symbol or a pick wins', async ({ page }) => {
    const diffuser = diffuserOf(await hvacIcons(page));

    // Plumbing (no type symbols): no CFM → the grid's first cell as before.
    await openQuickTab(page);
    const first = await page.evaluate(() => window.App.getOrderedIcons()[0].value);
    await page.click('#counterQuickCountAdd');
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect((await lastCounter(page)).icon).toBe(first);
    expect((await lastCounter(page)).cfm).toBeUndefined();

    // Plumbing + CFM, no pick → the diffuser (the preview swatch shows it first).
    await openQuickTab(page);
    await page.locator('#counterQuickCountCfm').fill('150');
    expect(await page.evaluate(() => document.querySelector('#counterQuickCountIcon svg path')?.getAttribute('d'))).toBe(diffuser);
    expect(await page.evaluate(() => document.querySelector('#counterQuickCountPanel .icon-cell.selected')?.getAttribute('data-path'))).toBe(diffuser);
    await page.click('#counterQuickCountAdd');
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect(await lastCounter(page)).toMatchObject({ icon: diffuser, cfm: 150 });

    // HVAC trade, "Return Grille" + CFM → the grille (the type symbol precedes the default).
    await openQuickTab(page);
    await page.click('#counterQuickCountTradeSegment [data-trade="hvac"]');
    await page.selectOption('#counterQuickCountType', 'Return Grille');
    await page.locator('#counterQuickCountCfm').fill('400');
    await page.click('#counterQuickCountAdd');
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    const grille = await lastCounter(page);
    expect(await iconNameOf(page, grille.icon)).toBe('Return Grille');
    expect(grille.cfm).toBe(400);

    // HVAC trade, a type without a symbol ("Fan Coil") + CFM → the diffuser; then an explicit pick wins.
    await openQuickTab(page);
    await page.selectOption('#counterQuickCountType', 'Fan Coil');
    await page.locator('#counterQuickCountCfm').fill('800');
    expect(await page.evaluate(() => document.querySelector('#counterQuickCountPanel .icon-cell.selected')?.getAttribute('data-path'))).toBe(diffuser);
    await page.click('#counterQuickCountAdd');
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect(await lastCounter(page)).toMatchObject({ icon: diffuser, cfm: 800 });

    await openQuickTab(page);
    await page.selectOption('#counterQuickCountType', 'Fan Coil');
    const pick = await page.evaluate(() => window.App.getOrderedIcons()[2].value);
    // The HVAC populate left the Custom Icons panel showing (the default type's symbol); pick from the built-in grid.
    await page.locator('#counterQuickCountPanel .counter-icon-tab[data-counter-quickcount-icon-tab="icon"]').click();
    await page.locator('#counterQuickCountIconGrid .icon-cell[data-path="' + pick + '"]').click();
    await page.locator('#counterQuickCountCfm').fill('800');
    await page.click('#counterQuickCountAdd');
    await page.waitForFunction(() => window.state.tool === window.App.TOOL.COUNTER);
    expect(await lastCounter(page)).toMatchObject({ icon: pick, cfm: 800 });
    expect(errors).toEqual([]);
  });
});
