// The landing's trade spotlight assets: every img/spotlight/ reference in index.html resolves to
// a committed file, every committed frame is referenced, and each trade has its six. The frames
// are generated by `node scripts/build-screenshots.js --set spotlight` (manual, not in check);
// this is the drift guard, the guides' link-integrity idiom.
const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
const refs = [...html.matchAll(/\/img\/spotlight\/([a-z0-9-]+\.jpg)/g)].map((m) => m[1]);
const dir = path.join(ROOT, 'img', 'spotlight');
const files = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith('.jpg')).sort() : [];

test('every spotlight frame index.html references is committed', () => {
  assert.ok(refs.length > 0, 'index.html references no spotlight frames');
  for (const r of new Set(refs)) assert.ok(files.includes(r), 'index.html references a missing frame: img/spotlight/' + r);
});

test('every committed spotlight frame is referenced by index.html', () => {
  const used = new Set(refs);
  for (const f of files) assert.ok(used.has(f), 'img/spotlight/' + f + ' is committed but not on the page');
});

test('each trade has its six frames, in order', () => {
  for (const trade of ['plumbing', 'electrical', 'hvac']) {
    const mine = refs.filter((r) => r.startsWith(trade + '-'));
    assert.strictEqual(mine.length, 6, trade + ' has ' + mine.length + ' frames, not 6');
    mine.forEach((r, i) => assert.ok(r.startsWith(trade + '-' + (i + 1) + '-'), trade + ' frame ' + (i + 1) + ' is ' + r));
  }
});
