/*
 * CountTooling service worker — installable PWA + offline app shell.
 *
 * Strategy (two-tier, same-origin only):
 *   - Navigations / HTML  → network-first (fresh shell when online), cache fallback offline.
 *   - Other static assets → cache-first against a version-stamped precache installed
 *     atomically, so the offline shell is always a coherent single version.
 * Cross-origin (Supabase REST/auth/realtime/storage range-requests/TUS/functions) and
 * all non-GET requests are passed straight through to the network, untouched.
 *
 * CACHE_VERSION, PRECACHE_URLS and PRECACHE_SHA256 below are GENERATED: do not edit by
 * hand. All three are stamped by `npm run build:sw` (and verified by
 * `npm run build:sw -- --check` in CI). PRECACHE_URLS is derived from app/index.html's tags
 * plus a short PRECACHE_EXTRA list in scripts/build-sw.js;
 * CACHE_VERSION is a joint content hash of every file in PRECACHE_URLS (change any
 * precached asset and the browser installs a fresh SW, precaches the new asset set, and
 * purges the old cache on activate — no manual bump to forget), and PRECACHE_SHA256 maps
 * each URL to its own sha256 so the install can VERIFY every fetched asset before caching
 * it. GitHub Pages deploys propagate non-atomically (per-file CDN caches, ~10 min): a
 * visit mid-deploy can fetch a mixed shell, and without verification the install would
 * poison the cache with it PERMANENTLY (cacheFirst never revalidates). A hash mismatch
 * aborts the install instead — the old SW stays, and the browser retries on a later
 * visit once the CDN has settled. The app's admin "global force reload" clears caches
 * as a backstop.
 */
const CACHE_VERSION = '2fda2a67a39e';
const CACHE_NAME = `counttooling-shell-${CACHE_VERSION}`;

// The full same-origin app shell. GENERATED by `npm run build:sw`, do not edit by hand:
// the root-absolute <script src>/<link href> tags in app/index.html (a new shell file needs
// only its tag), the fonts fonts.css names, the icons the manifest names, and PRECACHE_EXTRA
// in scripts/build-sw.js (the few assets fetched at run time by code). config.local.js is
// intentionally excluded (document.write, gitignored / localhost-only, would 404 the
// install). The app lives at /app/ (the marketing site at / is plain static HTML, outside
// the SW scope).
const PRECACHE_URLS = [
  // app/index.html: every root-absolute <script src> and <link href>, document order
  '/favicon.ico',
  '/icons/favicon.svg',
  '/manifest.webmanifest',
  '/icons/apple-touch-180.png',
  '/vendor/fonts/fonts.css',
  '/config.js',
  '/vendor/pdf.min-3.11.174.js',
  '/vendor/pdf-lib-1.17.1.min.js',
  '/vendor/html2canvas-1.4.1.min.js',
  '/vendor/jspdf.umd-2.5.1.min.js',
  '/vendor/supabase-js-2.108.0.min.js',
  '/vendor/tus-js-client-4.3.1.min.js',
  '/styles.css',
  '/icons.js',
  '/icons-custom.js',
  '/icon-render.js',
  '/geometry.js',
  '/line-metrics.js',
  '/conductor-model.js',
  '/circuit-model.js',
  '/bid-check-model.js',
  '/tag-model.js',
  '/sheet-title-model.js',
  '/support-model.js',
  '/water-model.js',
  '/fitting-model.js',
  '/duct-model.js',
  '/bid-basis-model.js',
  '/status-hint-model.js',
  '/canvas-legend.js',
  '/canvas-draw.js',
  '/render-service.js',
  '/constants.js',
  '/zoom-ladder.js',
  '/hotkeys.js',
  '/recent-colors.js',
  '/recent-drops.js',
  '/recent-bids.js',
  '/quick-keys-model.js',
  '/idb.js',
  '/format.js',
  '/save-utils.js',
  '/annotation-model.js',
  '/undo-stack.js',
  '/save-engine.js',
  '/pdf-tile-cache.js',
  '/app.js',
  '/features/canvas-repair.js',
  '/features/view-only.js',
  '/features/save-project.js',
  '/features/pdf-intake.js',
  '/features/line-color.js',
  '/features/custom-icon-upload.js',
  '/features/note.js',
  '/features/zoom.js',
  '/features/zoom-rail.js',
  '/features/manage-icons.js',
  '/features/multiply-zone-settings.js',
  '/features/scale-zone-settings.js',
  '/features/export-pdfs.js',
  '/features/bid-basis.js',
  '/features/legend-settings.js',
  '/features/page-settings.js',
  '/features/counter-settings.js',
  '/features/line-type-settings.js',
  '/features/choose-create-line-type.js',
  '/features/scale.js',
  '/features/groups.js',
  '/features/grid.js',
  '/features/quick-line.js',
  '/features/counter.js',
  '/features/save-status.js',
  '/features/status-bar.js',
  '/features/turn-in.js',
  '/features/manage-projects.js',
  '/features/hand-off.js',
  '/features/user-admin.js',
  '/features/load-project.js',
  '/features/bid-board.js',
  '/features/review-flow.js',
  '/features/copy-project.js',
  '/features/prepare-pdf.js',
  '/features/quick-modals.js',
  '/features/pdf-bundle.js',
  '/features/item-details.js',
  '/features/output.js',
  '/features/rfi-flags.js',
  '/features/notes-ledger.js',
  '/features/share-links.js',
  '/features/import-clear.js',
  '/features/zone-modals.js',
  '/features/restore-last-session.js',
  '/features/summary-detail.js',
  '/features/room-sizer.js',
  '/features/burger-menu.js',
  '/features/bid-chip.js',
  '/features/header-more.js',
  '/features/canvas-layers.js',
  '/features/ghost.js',
  '/features/canvas-switcher.js',
  '/features/summary-list.js',
  '/features/my-settings.js',
  '/features/project-settings.js',
  '/features/palette-insights.js',
  '/features/user-activity.js',
  '/features/user-activity-overview.js',
  '/features/tool-context-menu.js',
  '/features/mark-context-menu.js',
  '/features/bend-override.js',
  '/features/lines-list.js',
  '/features/pages-list.js',
  '/features/sidebar-lists.js',
  '/features/quick-keys.js',
  '/features/keyboard-map.js',
  '/features/floating-panel.js',
  '/features/chain.js',
  '/features/drop-mode.js',
  '/features/duct-tool.js',
  '/features/duct-size-popover.js',
  '/features/duct-fittings.js',
  '/features/duct-sidebar.js',
  '/features/duct-schedule.js',
  '/features/duct-suggest.js',
  '/features/water-fixtures.js',
  '/features/water-runs.js',
  '/features/water-size.js',
  '/features/water-schedule.js',
  '/features/water-bidcheck.js',
  '/features/duct-callouts.js',
  '/features/drop-peek.js',
  '/features/highlight-labels.js',
  '/features/hotkey-peek.js',
  '/features/esc-ladder.js',
  '/features/child-counts.js',
  '/features/conductors.js',
  '/features/circuits.js',
  '/features/rules.js',
  '/features/bid-check.js',
  '/features/duct-bidcheck.js',
  '/features/tag-reader.js',
  '/features/tutorial.js',
  '/features/lessons.js',
  '/features/learn-words.js',
  '/features/learn-taps.js',
  '/features/course-plumbing.js',
  '/features/course-electrical.js',
  '/features/course-hvac.js',
  '/features/demo-track.js',
  '/features/demo-hvac.js',
  '/features/demo-electrical.js',
  '/features/demo-plumbing.js',
  '/features/tour-blank.js',
  '/features/twin-badge.js',
  '/features/auth-magic-link.js',
  '/report.js',
  // /vendor/fonts/fonts.css: the font files it names
  '/vendor/fonts/dmmono-400-normal-latin-ext.woff2',
  '/vendor/fonts/dmmono-400-normal-latin.woff2',
  '/vendor/fonts/dmmono-500-normal-latin-ext.woff2',
  '/vendor/fonts/dmmono-500-normal-latin.woff2',
  '/vendor/fonts/dmsans-300-normal-latin-ext.woff2',
  '/vendor/fonts/dmsans-300-normal-latin.woff2',
  '/vendor/fonts/dmsans-400-normal-latin-ext.woff2',
  '/vendor/fonts/dmsans-400-normal-latin.woff2',
  '/vendor/fonts/dmsans-500-normal-latin-ext.woff2',
  '/vendor/fonts/dmsans-500-normal-latin.woff2',
  '/vendor/fonts/dmsans-600-normal-latin-ext.woff2',
  '/vendor/fonts/dmsans-600-normal-latin.woff2',
  '/vendor/fonts/instrumentserif-400-italic-latin-ext.woff2',
  '/vendor/fonts/instrumentserif-400-italic-latin.woff2',
  '/vendor/fonts/instrumentserif-400-normal-latin-ext.woff2',
  '/vendor/fonts/instrumentserif-400-normal-latin.woff2',
  '/vendor/fonts/barlowcondensed-v13-400-normal-latin.woff2',
  '/vendor/fonts/barlowcondensed-v13-500-normal-latin.woff2',
  '/vendor/fonts/barlowcondensed-v13-600-normal-latin.woff2',
  '/vendor/fonts/barlowcondensed-v13-700-normal-latin.woff2',
  // /manifest.webmanifest: the install icons it names
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/maskable-512.png',
  // PRECACHE_EXTRA in scripts/build-sw.js: fetched at run time, no tag names them
  '/app/',
  '/app/index.html',
  '/render-worker.js',
  '/vendor/pdf.worker.min-3.11.174.js',
  '/rules/rules.json',
  '/guides/words.json',
];

// Per-file integrity hashes for the verified install. GENERATED by
// `npm run build:sw` — do not edit by hand (see the header comment).
const PRECACHE_SHA256 = {
  '/favicon.ico': '245190b9033ded10d89660935858c3e9fe2046e24c1c9271c9f1067eced35ad4',
  '/icons/favicon.svg': '5e4845129109e7312a2e0b538c99cad4121dec3ad210f9db6788b85faace59b5',
  '/manifest.webmanifest': '91c2a30960da9245e4472fb4b3c2ba818a505179d0c4cd58a35e53ae3c0722df',
  '/icons/apple-touch-180.png': 'a3cc9422d951a7f34950c199e4f5520eff022c706cb08915be24cb3bdd723ac6',
  '/vendor/fonts/fonts.css': 'c7b3c780401eeeb7553f988499fbae1a86fcb7563e13b50615e0c009e83c3b95',
  '/config.js': '455a751857efe37a6c08d3922448bca7f57767b923e39826239a6f187608b05a',
  '/vendor/pdf.min-3.11.174.js': '5b5799e6f8c680663207ac5b42ee14eed2a406fa7af48f50c154f0c0b1566946',
  '/vendor/pdf-lib-1.17.1.min.js': '0f9a5cad07941f0826586c94e089d89b918c46e5c17cf2d5a3c6f666e3bc694f',
  '/vendor/html2canvas-1.4.1.min.js': 'e87e550794322e574a1fda0c1549a3c70dae5a93d9113417a429016838eab8cb',
  '/vendor/jspdf.umd-2.5.1.min.js': '98ccf17aa10c20bb1301762618fcc9b6ab3a4e7f26b6071d64d0b41154df3875',
  '/vendor/supabase-js-2.108.0.min.js': '005a6b7d396160fbe924316baa98adf198dc6f99a63412e27edec9675c225270',
  '/vendor/tus-js-client-4.3.1.min.js': '8cbb1b63fccc3bba0ae73ad1deb160ce046c3750851d0c3e94921ae3ef070eb8',
  '/styles.css': '6b55ca692b4f36901de21dbc0750519a77fa67fe9588c0a7cb91fe1a60e07be5',
  '/icons.js': 'bb3c3506a859d25685287d0c1d3afb3231601754555aea403505e7ca8d68779b',
  '/icons-custom.js': 'efe6b960301031a5fb40abc2f54de18798e19f4b7b04e0eccb81b47f1e9cacad',
  '/icon-render.js': '41b09b835c3898be95b013b27a6c11e1453c629cb811326d49fdcbfec19439d8',
  '/geometry.js': 'a0853ae21cf0fd3f41bd471414da16650dc0dcdd68006b30cfa473817d394df0',
  '/line-metrics.js': 'a6c7469a00abd2eca529c6d611ef08fab5dc219237dbc93d2dd72c81572fcadf',
  '/conductor-model.js': '9b48dee4874ad9692d0e318813c88463aab08f107d46562015b92d99a3f074a9',
  '/circuit-model.js': '19e0de705524e0390476d4f9346008ffdad190786c8b1720eb4a8dab64febc09',
  '/bid-check-model.js': 'bf457af6cff7152c0a6ba07420ee093a645fa6cd20e0b42c1adbfeb9453db733',
  '/tag-model.js': '05825b59db918b615d9354a57088c6e735f39b6df0a5bac7a639b4136265ee6b',
  '/sheet-title-model.js': 'f4af651077942b4b14a4eec23effcbcf6099713125031270a868d3a21a2737cd',
  '/support-model.js': 'a1fba42dfd24cfc5dfd662e6dcb67bced82bb656f7589b828110f5d08088eb69',
  '/water-model.js': '665c87b463a31490882a1731c2c48fdb385feb95b20b91d103b8adf894ad07a8',
  '/fitting-model.js': '60aef6daecbf4ea7205224b2656d3bdaca033fa9ce9f896885f56e5618b6b9b1',
  '/duct-model.js': '96e23b4fc7f0bb91e2c3bcd370f727463225dd9d35dfdba15f1c86ee8409f22c',
  '/bid-basis-model.js': '07bd80cd2693d6e97d9cb41d151b46a8b0f4e0cc2b8d822797e58a600e85f4f4',
  '/status-hint-model.js': 'b55e1c0217607899538609aa147fe19649650d1b8cfd141469277199f576d240',
  '/canvas-legend.js': '534a6a31a2006d86b4beeadc1f672ac54a9c42a25314d9c09c84489b5e212c82',
  '/canvas-draw.js': '451aac75c1641df713ac04cdfc2d86f5efef675b3c91746611a8236bf04832d5',
  '/render-service.js': '077e7474ba588a262ca7fe01183271af85d8a9a105e4c90cb1ebd5ed7d8ab0da',
  '/constants.js': '6a971107e97e783432277932b31fffc4d1e4579abaf822f5b62058dc7de07971',
  '/zoom-ladder.js': 'c8396a9b8610ce94c703b575e3180ad3152d17a5b23c9e576c8d45b980005ba3',
  '/hotkeys.js': '130b8f25fbb3a6fb46ed4e3a7f20fbc001d007743a9aba241824739bffdb39ce',
  '/recent-colors.js': '01a7af7515a037ac51f0819601156c64035b903ce55a2739a5393988792285a7',
  '/recent-drops.js': '3b04d7b96c6260858a3ce9de59a9e862fa88ddf3e563de3ef46d354020358b7b',
  '/recent-bids.js': '0c27598ee2b7013f553eef5456b257935bc1de5810db43660afd4b74975a89bb',
  '/quick-keys-model.js': 'a0384c2d3771161af50dee2c103894f586bf09b3a51936edfb2a3c24d7af8deb',
  '/idb.js': 'ae6bf34b5675883ed82c23229597911165036a2f12e7566dbbd949b86f316f05',
  '/format.js': '8957d41b6a883fe315b79aaf6b4b34f89cc0063970394f00aa16fcbd8a0339a2',
  '/save-utils.js': '1d23d447f52e53e2a8c36a17c89c53a522c6fdd74281a157b4893ed794d8a841',
  '/annotation-model.js': '7b9477332ade340178561eece0a5c2259b9251979e966de2b023a453935c368c',
  '/undo-stack.js': '34180b25071008b6f29c8b3c2529faa29e21c2957e9ee26b5510e5ef5750f69c',
  '/save-engine.js': 'd620a2ade982357362d0e7dd9c701df90a3cffe47e66f780dcd1d24b81fda918',
  '/pdf-tile-cache.js': 'd9d520d6399480191df2b97038ce0b453803666d79f1b804a995484e98fc5772',
  '/app.js': '3a16cc7fed383b4fffd31090f8f199e11357b792afa46befa7c282f1a650d966',
  '/features/canvas-repair.js': 'b2dca5c86174ed9589d0c44091d9265c2e3af039c08cf4422eb151fa5fd8ec02',
  '/features/view-only.js': 'f4e6c4f5601c089aa1001a9583c409e61d9090a639acd6a69994bccd6ca0dbcc',
  '/features/save-project.js': '6f01819d040f4a05ee9805ccabdc5170973429a39d5d0c3e54381a0d43866ad2',
  '/features/pdf-intake.js': 'b349284f0ca3a2bcc3d4cc14e1811e226fbbce7e10ce0816f2555a113028b199',
  '/features/line-color.js': '2fd4c7594f1a3686fd9323b7bc4d97f5b9c151b32475d5a4428062a075378ecb',
  '/features/custom-icon-upload.js': 'cf0d6731862f3baa8b7ed55cbfc89759df42934f52d1c22586ac37d3b406ab06',
  '/features/note.js': 'b7cc88aa00ac8a2450c59299959108ae3bd5b18b0e420fd61264533c23347d6b',
  '/features/zoom.js': 'cceb56f7ae4c91124aa17b246b276b9796463dc27ce93835a849f5a3d31f31fc',
  '/features/zoom-rail.js': '02b27244833dc50a8eaf688070a486e2a0e167e3bd193ae89499538df9372da3',
  '/features/manage-icons.js': '9da0efb19f2e86b1d3b2f1d9bd6eda2a12ae3e307abba3a9f2c9b5da8d646382',
  '/features/multiply-zone-settings.js': 'e808757a5758d7c0ba64d989ef3f6e051266b40a26ff01ae9ea8187b7b834dee',
  '/features/scale-zone-settings.js': '67a8a802e7aeaf629a235dbd0e4d9c42ea5c746412ae6749b90ecf35be7a9c9f',
  '/features/export-pdfs.js': '004bbd57e77f5a7435dad4ff22265a5c811fc85fa99b1a547a3895033bb6e15c',
  '/features/bid-basis.js': '1effb492871d0ec5fb3de46d4f9e72e25efedac4708cd9c86af1e735abbd352c',
  '/features/legend-settings.js': '32ec67d0fb6d38e4c12dcb365fdef225b5d2d4f6e6076b8183f9babcfb739528',
  '/features/page-settings.js': '1fdc5d2e5cd24d30a6cace38d14c98344bb147cf5a1c098d51228f6d77317845',
  '/features/counter-settings.js': '560ecc49be5545c1b800bb9fbc361e23ebd4f8612b9c530a5b446752e0769a34',
  '/features/line-type-settings.js': '73b1c33738ee4305fd50e16033b7e28fe3d6c9bcee0f5a102158b1ad44e17f11',
  '/features/choose-create-line-type.js': '52a26d1488d16ba81196256dfc525d0cb369e3c7db8a771ffa44f122ed4009a5',
  '/features/scale.js': '37d0a220079c2141d1d8dc65a0c9af0b9e504aa64f3fec7ada0da0f176f3878d',
  '/features/groups.js': 'e0bd328a87f18cbc809323da030e287955861771502bf9e6d2b6c4a00b283176',
  '/features/grid.js': 'bfe967382b165655bc9d3bb00b2465cb4e1ffd612e05c46121ce2704764cbe9a',
  '/features/quick-line.js': '8a68ae922487c3fc962fa71017f1efcf475fdc6f44ddbdb5bedcd3ed9159393a',
  '/features/counter.js': '32840a4096b08411bd59e1c25afc1093f6acea091cc3c49d70c5becf43dfc2a6',
  '/features/save-status.js': 'd656c3245ae372bbfca907c6ca90d7367fc56e284919d625fbfe1720209fa33a',
  '/features/status-bar.js': '56a8fb6545f2e4038d421d3a936c877d89a03d306ee80e229c5661c2aa00d475',
  '/features/turn-in.js': 'dc3bc2f18ad840d5670f2e8cf08c08aeedb0d60552215b589d8e875596aaeae3',
  '/features/manage-projects.js': 'e462989f4621db4375471bb3deb05fe9c707345d1e4bda9394d302f1f8bb02fe',
  '/features/hand-off.js': 'e996c7300432489bcb8e1c9a02539278a7ac3ffbf2daaabce4922b4875e10c23',
  '/features/user-admin.js': '2abd3029bdf2950310af9c19fb302b416976922bad3f4142db55626e3a229128',
  '/features/load-project.js': 'c0d46b903bf80f5b033a2bfe03f91871c687c20ee5d538d25ef523c1e87fb878',
  '/features/bid-board.js': 'a7aa87b4f720c139b2407e4c09368495632f83189c214e3369a526839ee47522',
  '/features/review-flow.js': '7dd1ac948e0031abab788666622873a143eeefd3315ed0b1cadb1a8083400bc5',
  '/features/copy-project.js': '7668abd5e8121edc27c3155882da4c252791455a5a7bdd4a6accbe36ef0bea09',
  '/features/prepare-pdf.js': '7468cb401fc5a29c1e3e6f3188c1e99396c6b7b5d5374d2cb7de0367a80e4c24',
  '/features/quick-modals.js': '052927460e00406495fea8cdb36c0e3cf816d455eb94cb764437bd40016ed527',
  '/features/pdf-bundle.js': '46ea83cea1b075c92f6e2086d60716f8f2840ab3b2b8000986e2912528f31809',
  '/features/item-details.js': '5b27cce6a33a4439ef426db2b55f03b0b93413b07f03e66044bfec646711cdb1',
  '/features/output.js': 'c68909c4b19ddb08e28b647725ec06ddefb7807089d831979796a1d042952d81',
  '/features/rfi-flags.js': '4321db07f601a5636f04d42a9e746498eb03ad1005213e2e248aad8e66fdb41b',
  '/features/notes-ledger.js': '291effbe0dcaf4fcbcbd4b8bc9e3371c5c8c8e1564d2b1a68d7db96bb03f7e92',
  '/features/share-links.js': '8988dea7364d6d7e9aeca68ef1276fea0e878e4057f2cfc22fe89f6e992220f7',
  '/features/import-clear.js': 'a60207b82190ff07ee6e0850a6264213da94de9a55b9e7fa77b6b0e90ffb8844',
  '/features/zone-modals.js': '1981de3740bb45e16edf901b9ed9d8dccbe7538f248f1c9a1ec16f271da856ab',
  '/features/restore-last-session.js': 'ed2940c780f2a184e9a09d5199010230427a5d7c6b9d9041088e413d6a24716b',
  '/features/summary-detail.js': '9e0ccaa95c895704d1130d33ec97aaf9d1ed02c250b63efde1ea111ba1fa9fb8',
  '/features/room-sizer.js': '5556016fc266fb8c1be0e3f4c07480f48f4c6a2510282833bf13e67690c79a7f',
  '/features/burger-menu.js': 'ace047ffd97c17d329ff3d2af9853c5439fcbe33e46619b5c22881da182dbe12',
  '/features/bid-chip.js': '5ae93765826726786ff26e08706ed415d86c29f4383ab364bbbf878531272568',
  '/features/header-more.js': '5ac497cb75bf94b20da440f4dfb4996cd6a6bbde2d5c7ee3a9b00e43d976f5de',
  '/features/canvas-layers.js': '4221ddc56bcd2447eb6bd7ecdb681872753d3808c4b228c17188975758077575',
  '/features/ghost.js': 'acb4822e886f15f3c93506de3354635c3b052aa25eb2dd0ed085d715d6c7b8c3',
  '/features/canvas-switcher.js': '89970ea9ae56c8bffa8f3fd0360ea4ba3e901bec1a772972117dcebe5acc9393',
  '/features/summary-list.js': '6b7a9f6eef9d3faa990e16577366c4f3a16b7484d20ff14fd449be3695237d85',
  '/features/my-settings.js': 'd3792711b4d9107dd53770c2ec09da1c1911882d0be95de63d86715170d67efa',
  '/features/project-settings.js': '5cc98ba642b73253c876e7af15107cb0f8c481b08a82f5a4765f12bbf046efac',
  '/features/palette-insights.js': '1086010487af658d7a0bb9c059ff4d9ad4f0ed1839a118f14667771a8c316b16',
  '/features/user-activity.js': '2548c3835c9870092c4e3ba6de191b1493b4a81b7739bd144d96dcf20fcb19eb',
  '/features/user-activity-overview.js': '70895b1093150ee2c4049540df9eb0a40f13af17868e482ad178dac7a7c02b10',
  '/features/tool-context-menu.js': 'b3eaa212bea057c6497afddaba467cc9ce0a03f4f922559b49b914824fbe1266',
  '/features/mark-context-menu.js': 'eca9d5c7e3faacd628e83c36644512de029898ef92b41b8487579de5885079b7',
  '/features/bend-override.js': '875ab8446dc799619494191dc2b3e62097c0d3193c64094686c82f096d7a284c',
  '/features/lines-list.js': '042729932059773f3acbd9c57268247f464d52549adf9cc3b42eab332f834b22',
  '/features/pages-list.js': 'a23c643abca9ee91fa3476a03fe8c3083e126ba76a1f5843af74889fb8766630',
  '/features/sidebar-lists.js': '54b1cc1ae24ba0196e5a5701a92291d31a86a6e9a8fa07ec5fc083e3f0a1bd18',
  '/features/quick-keys.js': 'f86e3fd57d7c6f9b440fcb2e75edad7b2fa14eedf52e02405bce8bcd6faed203',
  '/features/keyboard-map.js': '88de003bb6819a8f55a7fbf81b5cd4941860e06e0eff2dc349c8be735978ac84',
  '/features/floating-panel.js': '83e2766c6827ab5479b6994197082bd45fd953887c3df33803fb5b94e7f0fb6e',
  '/features/chain.js': '0214116e318a5915f4c5fd0490d70966119878ec37ed0cc947cb3aab90093229',
  '/features/drop-mode.js': '99d5af237206b6fb9d02128e9a78de5316231fa94dbf8f80ca7ea69049df33ff',
  '/features/duct-tool.js': '7118fec2bad0099af8333dda5d24e18a7bd6de98f1c72baa56579667f812df64',
  '/features/duct-size-popover.js': '55eee93f772e8b1b79f987595fdb085c29573be3d0f45b9d9608d0c27e1180d6',
  '/features/duct-fittings.js': 'bb4cc43a289d3942f06cc56ae52dfed5676e9a1b28d64d5600bf15dedce662cf',
  '/features/duct-sidebar.js': '6f5ec590c618d7c6870d47901265d4f90452a090fd563f98e4083d9171e89555',
  '/features/duct-schedule.js': 'a1e566e0be2141bd00f26966dc6facc921d46766eb5107e2d5acba84f9a5d344',
  '/features/duct-suggest.js': '3e774c3e0f012908e7fce5b4ebddc8aa0e423cebed134a7a135dbf0f2621dcbe',
  '/features/water-fixtures.js': '063e59f7bd9077c70f40d4684f0bc175480257dd25e2d9c456474f8c9545a2e2',
  '/features/water-runs.js': '87e1ec21e43d8c3c1dbe4ac11f0743d985500911cf7eb01e2e21108fd86c404e',
  '/features/water-size.js': '0881807a988b25e8fde8fae545f543f53b3a2f9d16017263e0d72e242e257052',
  '/features/water-schedule.js': 'e32cef8b52432e26fd91e140fe0c89da7eac40f3f67090964c24602830c9aa30',
  '/features/water-bidcheck.js': '6254e38fdcc257b2ca7c6820762e63b78d5a3a1569ad95dfc98b787f15027a21',
  '/features/duct-callouts.js': '45b05eca07b2a52f8cc08ad2f5d443053c08f7fe14a58c5d1f46641425f9e71a',
  '/features/drop-peek.js': 'dcd5c8370524158cf579e747c155167e7407e7fbeaaeba4cbac7866fcf3bfb69',
  '/features/highlight-labels.js': 'd06176449b44642d2205bfb485a570622eec921c4c458fb4f8f31d92c662bb28',
  '/features/hotkey-peek.js': 'd48166e9a596417cb3415123d020c95eaafee05a50c0db042e89aac5b607f109',
  '/features/esc-ladder.js': 'eaf25dc1607fbfb0cf1be5adce68e2694126c3c9073f493612f9ad3342abe3e2',
  '/features/child-counts.js': '24a3e8c124579d2c63e18a74410a9cd26869eba89db97e780bad23fe9ea6b4fd',
  '/features/conductors.js': '97c55f9fc2f18bcd5420340b6b13cb85c64295d3eec4d523c93c14d90f7d960c',
  '/features/circuits.js': '1b5fcf486faf36f2333bde65bc4c75d3ad314710fee01b8874333cebc46e13de',
  '/features/rules.js': '2c3b3db98897ff9eb380b172dfc3582c6aac6fd0fd4b8d47c3f40a0cc9bbf01c',
  '/features/bid-check.js': '71a6725a139558fe95784dad5ce1143429f228c80bb275ecf45252e9ea5d9f91',
  '/features/duct-bidcheck.js': '3b9cdc4940f7b82fccc6c2999543dc0968422166e68ad67096f1cb7de2714d39',
  '/features/tag-reader.js': '2741d149a5dd307b838993c508928fc0ad61dbd607f2fae828bca1f082fbb6da',
  '/features/tutorial.js': '58223a1e07962e8703cf4a2dcce4576d53875ebddf83e6ebb076b22a6d6a5282',
  '/features/lessons.js': '31c80defbe3f8d000d06b1c9747584c6f3968ec64fb0e915e1fa418d494c43fd',
  '/features/learn-words.js': 'bbd2524b0ac6cc25383ddd83c13db7c5274ad94046da45c8343a82780250ab68',
  '/features/learn-taps.js': '13b8328e1727ef436db981a8073e2cc2aed4f5ece88619df3d2647ebb3ff7a43',
  '/features/course-plumbing.js': '517415f5648c2772573c2cb8b097230d1286168708f00fd981758978795e2afd',
  '/features/course-electrical.js': 'b51593f0600ed5dbee381ba27aea519f51afc41c732334991a5ee176a50fd69b',
  '/features/course-hvac.js': '47d8f95ec237c2ca93b52f6af17a6f93cfd9676cd67280e9b0449db7f9b230c5',
  '/features/demo-track.js': '001eddde2f8f92e344330a797682529da5abc3851c2a35902c7266d619cbfaee',
  '/features/demo-hvac.js': '2fb02a33c04749ea0d6c39be6e247f91722ff0f06b3a45efdece92db3ffb9651',
  '/features/demo-electrical.js': '76f5483f0302ddfaefc1c6810c73bd3a8401c299ea4277ae4ad6ece2ce6acd5f',
  '/features/demo-plumbing.js': 'ab7ea12e6c7f7e86cff0f6cc01c860e69726bf52abde25c6d42f1f4d5594ffc5',
  '/features/tour-blank.js': '4d09700abf75d43b6f262f964ea77b40f408c0564f4634744531cca9a51e423e',
  '/features/twin-badge.js': '714ef6850ba7f430ff181ec8c91795485553e9c27dae9c8ebd40ea75d63943bf',
  '/features/auth-magic-link.js': '56c0ffb89518846f1ac22c7ed458ffdc8d991e45838784e51203696689e5cdc5',
  '/report.js': '7a74dd1f8c83e9bb057405533f91d38c55a87ba76bacb384a9c9689b229dc679',
  '/vendor/fonts/dmmono-400-normal-latin-ext.woff2': '7f8712cbbd64135f9e74a527475a97cd8c5a49d8e0a1de7a65f8e2c30c5214d9',
  '/vendor/fonts/dmmono-400-normal-latin.woff2': 'fd7521f3531a5ccfc655b25c4f22e9871df3ec141ad79bb27fde20d0df347b6d',
  '/vendor/fonts/dmmono-500-normal-latin-ext.woff2': 'e284f2a17fc9cca89cc30f496945bd9a2903010944a9469fb357924da21b6f6c',
  '/vendor/fonts/dmmono-500-normal-latin.woff2': '0e263db52797086e763679c54f84ded8cc1249879bc27dca2bd5dd446f6d9f36',
  '/vendor/fonts/dmsans-300-normal-latin-ext.woff2': '219b02c7d8884817d3d6ad4c8771f2c000ce4c5669a67ef4e2e5617ffa25c4cc',
  '/vendor/fonts/dmsans-300-normal-latin.woff2': '468d56b6b25b05b70190b6c233d773f6f1770e8579827ce022a57f03fa8002fb',
  '/vendor/fonts/dmsans-400-normal-latin-ext.woff2': '219b02c7d8884817d3d6ad4c8771f2c000ce4c5669a67ef4e2e5617ffa25c4cc',
  '/vendor/fonts/dmsans-400-normal-latin.woff2': '468d56b6b25b05b70190b6c233d773f6f1770e8579827ce022a57f03fa8002fb',
  '/vendor/fonts/dmsans-500-normal-latin-ext.woff2': '219b02c7d8884817d3d6ad4c8771f2c000ce4c5669a67ef4e2e5617ffa25c4cc',
  '/vendor/fonts/dmsans-500-normal-latin.woff2': '468d56b6b25b05b70190b6c233d773f6f1770e8579827ce022a57f03fa8002fb',
  '/vendor/fonts/dmsans-600-normal-latin-ext.woff2': '219b02c7d8884817d3d6ad4c8771f2c000ce4c5669a67ef4e2e5617ffa25c4cc',
  '/vendor/fonts/dmsans-600-normal-latin.woff2': '468d56b6b25b05b70190b6c233d773f6f1770e8579827ce022a57f03fa8002fb',
  '/vendor/fonts/instrumentserif-400-italic-latin-ext.woff2': 'a04fc7ed18a8037149ce0bfda58076709d8e0840e136ed00abbdc196b7992443',
  '/vendor/fonts/instrumentserif-400-italic-latin.woff2': '6ee678c33f388dd7ba59700ebea635deb98821baafd817b09891f7927177f702',
  '/vendor/fonts/instrumentserif-400-normal-latin-ext.woff2': 'a8c4bd7cd7073180e740d2d83a616b5cb0845579b73207eeafeae8532e70c901',
  '/vendor/fonts/instrumentserif-400-normal-latin.woff2': '60c06664b5a95c7de6cc3e00d1f9034d78bd1e40b564016b241674449a067d4d',
  '/vendor/fonts/barlowcondensed-v13-400-normal-latin.woff2': '0e2a408159b32d8105bcd1a0a4d6222fcee375a84fb62703c614ce34d8bb68bb',
  '/vendor/fonts/barlowcondensed-v13-500-normal-latin.woff2': '31ff5e6e96a096fde4d78bc838719e69b093db2d0b062b96e423c065a6d1b2b1',
  '/vendor/fonts/barlowcondensed-v13-600-normal-latin.woff2': '5bc49d41f32810a114765314392332ce2acae2276635eee265a50319a12c1b49',
  '/vendor/fonts/barlowcondensed-v13-700-normal-latin.woff2': 'e3e520cb7468f2efd60bc2ce96694567c3312f4ef414fffbe605e3ad146b24e6',
  '/icons/icon-192.png': 'c807a7a2fda05dc5a74c60f16d7199bc1c617aa36948acc20e3712a412f943c2',
  '/icons/icon-512.png': '386919ae854bc73fd0c8fa39bcb8f16d2496ce0b487792ca17b0924d7a8eb137',
  '/icons/maskable-512.png': 'a5c54fa0ab699678992c5e5473721804d24257762a859f8c2183fb4049bfa164',
  '/app/': '4b4dcd9f80faa5c355e6e3e0520a226bb344ea714a86615283559f4e99ddadfe',
  '/app/index.html': '4b4dcd9f80faa5c355e6e3e0520a226bb344ea714a86615283559f4e99ddadfe',
  '/render-worker.js': '97409f02a7150a5f9b5e456769083b49dca0c7baaae0263a34e2fc7a1d23a54d',
  '/vendor/pdf.worker.min-3.11.174.js': 'feabdf309770ed24bba31a5467836cdc8cf639c705af27d52b585b041bb8527b',
  '/rules/rules.json': 'bf4f68f9b25bd2bbc13e382bd204fce243c23945c8cf7bcb57da828f652e122b',
  '/guides/words.json': '545c8da0369d03b21cf601fa687584ffedea0afdd434f87fdf1f289a3e4406be',
};

self.addEventListener('install', (event) => {
  event.waitUntil(precacheVerified().then(() => self.skipWaiting()));
});

// The verified replacement for cache.addAll: fetch every precache asset
// straight from the origin (cache: 'reload' — the HTTP cache could hand back a
// pre-deploy body that no longer matches the new sw.js's hashes), check its
// sha256 against PRECACHE_SHA256, and cache only verified bytes. ANY mismatch
// or failed fetch rejects the install: a mid-deploy CDN serving a mixed shell
// can no longer be captured into the version-stamped cache. Entries verified
// before the failure are already cache.put — harmless: they are byte-correct
// for THIS version, activate never runs on a failed install, and a later
// successful install re-puts everything. Browsers without crypto.subtle skip
// the check for that entry (yesterday's behavior).
async function precacheVerified() {
  const cache = await caches.open(CACHE_NAME);
  await Promise.all(PRECACHE_URLS.map(async (url) => {
    const res = await fetch(new Request(url, { cache: 'reload' }));
    if (!res || !res.ok) throw new Error('precache fetch failed (' + (res && res.status) + '): ' + url);
    const expected = PRECACHE_SHA256[url];
    if (expected && self.crypto && self.crypto.subtle) {
      const digest = await crypto.subtle.digest('SHA-256', await res.clone().arrayBuffer());
      const hex = Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, '0')).join('');
      if (hex !== expected) throw new Error('precache hash mismatch (mid-deploy CDN?): ' + url);
    }
    await cache.put(url, res);
  }));
}

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('counttooling-shell-') && k !== CACHE_NAME)
          .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  // Non-GET (Supabase writes, TUS PATCH/POST, etc.) → straight to network.
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Cross-origin (Supabase REST/auth/realtime/storage range-requests/functions, etc.) → network.
  if (url.origin !== self.location.origin) return;

  // config.local.js is intentionally outside the precache (gitignored,
  // localhost-only) — never runtime-cache it either, or a dev's credential
  // edits get pinned to the first version cacheFirst ever saw.
  if (url.pathname === '/config.local.js') return;

  const isHtml = req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html');
  event.respondWith(isHtml ? networkFirst(req) : cacheFirst(req));
});

// Network-first for the entry document: always boot the freshest shell online, fall back
// to the precached HTML offline.
async function networkFirst(req) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const fresh = await withTimeout(fetch(req), 4000);
    if (fresh && fresh.ok) { cache.put(req, fresh.clone()).catch(() => {}); return fresh; }
    if (fresh) return fresh;
    throw new Error('no-response');
  } catch {
    return (await cache.match(req))
      || (await cache.match('/app/index.html'))
      || (await cache.match('/app/'))
      || new Response('Offline', { status: 503, statusText: 'Offline' });
  }
}

// Cache-first against the version-stamped precache: guarantees a coherent shell version
// offline; only hits the network for a precache miss.
async function cacheFirst(req) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(req);
  if (cached) return cached;
  try {
    const fresh = await fetch(req);
    if (fresh && fresh.ok && fresh.type === 'basic') cache.put(req, fresh.clone()).catch(() => {});
    return fresh;
  } catch {
    return new Response('', { status: 504, statusText: 'Offline' });
  }
}

function withTimeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('timeout')), ms);
    promise.then(
      (v) => { clearTimeout(timer); resolve(v); },
      (e) => { clearTimeout(timer); reject(e); }
    );
  });
}
