/*
 * CountTooling service worker — installable PWA + offline app shell.
 *
 * Strategy (two-tier, same-origin only):
 *   - Navigations / HTML  → network-first (fresh shell when online), cache fallback offline.
 *   - Other static assets → cache-first against a version-stamped precache installed
 *     atomically, so the offline shell is always a coherent single version.
 * Cross-origin (Supabase REST/auth/realtime/storage range-requests/TUS/functions) and
 * all non-GET requests are passed straight through to the network, untouched.
 *
 * CACHE_VERSION, PRECACHE_URLS and PRECACHE_SHA256 below are GENERATED: do not edit by
 * hand. All three are stamped by `npm run build:sw` (and verified by
 * `npm run build:sw -- --check` in CI). PRECACHE_URLS is derived from app/index.html's tags
 * plus a short PRECACHE_EXTRA list in scripts/build-sw.js;
 * CACHE_VERSION is a joint content hash of every file in PRECACHE_URLS (change any
 * precached asset and the browser installs a fresh SW, precaches the new asset set, and
 * purges the old cache on activate — no manual bump to forget), and PRECACHE_SHA256 maps
 * each URL to its own sha256 so the install can VERIFY every fetched asset before caching
 * it. GitHub Pages deploys propagate non-atomically (per-file CDN caches, ~10 min): a
 * visit mid-deploy can fetch a mixed shell, and without verification the install would
 * poison the cache with it PERMANENTLY (cacheFirst never revalidates). A hash mismatch
 * aborts the install instead — the old SW stays, and the browser retries on a later
 * visit once the CDN has settled. The app's admin "global force reload" clears caches
 * as a backstop.
 */
const CACHE_VERSION = '29b18dbfb123';
const CACHE_NAME = `counttooling-shell-${CACHE_VERSION}`;

// The full same-origin app shell. GENERATED by `npm run build:sw`, do not edit by hand:
// the root-absolute <script src>/<link href> tags in app/index.html (a new shell file needs
// only its tag), the fonts fonts.css names, the icons the manifest names, and PRECACHE_EXTRA
// in scripts/build-sw.js (the few assets fetched at run time by code). config.local.js is
// intentionally excluded (document.write, gitignored / localhost-only, would 404 the
// install). The app lives at /app/ (the marketing site at / is plain static HTML, outside
// the SW scope).
const PRECACHE_URLS = [
  // app/index.html: every root-absolute <script src> and <link href>, document order
  '/favicon.ico',
  '/icons/favicon.svg',
  '/manifest.webmanifest',
  '/icons/apple-touch-180.png',
  '/vendor/fonts/fonts.css',
  '/config.js',
  '/vendor/pdf.min-3.11.174.js',
  '/vendor/pdf-lib-1.17.1.min.js',
  '/vendor/html2canvas-1.4.1.min.js',
  '/vendor/jspdf.umd-2.5.1.min.js',
  '/vendor/supabase-js-2.108.0.min.js',
  '/vendor/tus-js-client-4.3.1.min.js',
  '/styles.css',
  '/icons.js',
  '/icons-custom.js',
  '/icon-render.js',
  '/geometry.js',
  '/line-metrics.js',
  '/conductor-model.js',
  '/circuit-model.js',
  '/bid-check-model.js',
  '/tag-model.js',
  '/sheet-title-model.js',
  '/support-model.js',
  '/water-model.js',
  '/fitting-model.js',
  '/duct-model.js',
  '/bid-basis-model.js',
  '/status-hint-model.js',
  '/canvas-draw.js',
  '/render-service.js',
  '/constants.js',
  '/zoom-ladder.js',
  '/hotkeys.js',
  '/recent-colors.js',
  '/recent-drops.js',
  '/recent-bids.js',
  '/idb.js',
  '/format.js',
  '/save-utils.js',
  '/annotation-model.js',
  '/undo-stack.js',
  '/save-engine.js',
  '/pdf-tile-cache.js',
  '/app.js',
  '/features/canvas-repair.js',
  '/features/view-only.js',
  '/features/save-project.js',
  '/features/pdf-intake.js',
  '/features/line-color.js',
  '/features/custom-icon-upload.js',
  '/features/note.js',
  '/features/zoom.js',
  '/features/zoom-rail.js',
  '/features/manage-icons.js',
  '/features/multiply-zone-settings.js',
  '/features/scale-zone-settings.js',
  '/features/export-pdfs.js',
  '/features/bid-basis.js',
  '/features/legend-settings.js',
  '/features/page-settings.js',
  '/features/counter-settings.js',
  '/features/line-type-settings.js',
  '/features/choose-create-line-type.js',
  '/features/scale.js',
  '/features/groups.js',
  '/features/grid.js',
  '/features/quick-line.js',
  '/features/counter.js',
  '/features/save-status.js',
  '/features/status-bar.js',
  '/features/turn-in.js',
  '/features/manage-projects.js',
  '/features/user-admin.js',
  '/features/load-project.js',
  '/features/bid-board.js',
  '/features/review-flow.js',
  '/features/copy-project.js',
  '/features/prepare-pdf.js',
  '/features/quick-modals.js',
  '/features/pdf-bundle.js',
  '/features/item-details.js',
  '/features/output.js',
  '/features/rfi-flags.js',
  '/features/notes-ledger.js',
  '/features/share-links.js',
  '/features/import-clear.js',
  '/features/zone-modals.js',
  '/features/restore-last-session.js',
  '/features/summary-detail.js',
  '/features/room-sizer.js',
  '/features/burger-menu.js',
  '/features/bid-chip.js',
  '/features/header-more.js',
  '/features/canvas-layers.js',
  '/features/ghost.js',
  '/features/canvas-switcher.js',
  '/features/summary-list.js',
  '/features/my-settings.js',
  '/features/palette-insights.js',
  '/features/user-activity.js',
  '/features/user-activity-overview.js',
  '/features/tool-context-menu.js',
  '/features/bend-override.js',
  '/features/lines-list.js',
  '/features/pages-list.js',
  '/features/sidebar-lists.js',
  '/features/quick-keys.js',
  '/features/keyboard-map.js',
  '/features/chain.js',
  '/features/drop-mode.js',
  '/features/duct-tool.js',
  '/features/duct-size-popover.js',
  '/features/duct-fittings.js',
  '/features/duct-sidebar.js',
  '/features/duct-schedule.js',
  '/features/duct-suggest.js',
  '/features/water-fixtures.js',
  '/features/water-runs.js',
  '/features/water-size.js',
  '/features/water-schedule.js',
  '/features/water-bidcheck.js',
  '/features/duct-callouts.js',
  '/features/drop-peek.js',
  '/features/highlight-labels.js',
  '/features/hotkey-peek.js',
  '/features/esc-ladder.js',
  '/features/child-counts.js',
  '/features/conductors.js',
  '/features/circuits.js',
  '/features/rules.js',
  '/features/bid-check.js',
  '/features/duct-bidcheck.js',
  '/features/tag-reader.js',
  '/features/tutorial.js',
  '/features/lessons.js',
  '/features/course-plumbing.js',
  '/features/course-electrical.js',
  '/features/course-hvac.js',
  '/features/tour-blank.js',
  '/features/twin-badge.js',
  '/features/auth-magic-link.js',
  '/report.js',
  // /vendor/fonts/fonts.css: the font files it names
  '/vendor/fonts/dmmono-400-normal-latin-ext.woff2',
  '/vendor/fonts/dmmono-400-normal-latin.woff2',
  '/vendor/fonts/dmmono-500-normal-latin-ext.woff2',
  '/vendor/fonts/dmmono-500-normal-latin.woff2',
  '/vendor/fonts/dmsans-300-normal-latin-ext.woff2',
  '/vendor/fonts/dmsans-300-normal-latin.woff2',
  '/vendor/fonts/dmsans-400-normal-latin-ext.woff2',
  '/vendor/fonts/dmsans-400-normal-latin.woff2',
  '/vendor/fonts/dmsans-500-normal-latin-ext.woff2',
  '/vendor/fonts/dmsans-500-normal-latin.woff2',
  '/vendor/fonts/dmsans-600-normal-latin-ext.woff2',
  '/vendor/fonts/dmsans-600-normal-latin.woff2',
  '/vendor/fonts/instrumentserif-400-italic-latin-ext.woff2',
  '/vendor/fonts/instrumentserif-400-italic-latin.woff2',
  '/vendor/fonts/instrumentserif-400-normal-latin-ext.woff2',
  '/vendor/fonts/instrumentserif-400-normal-latin.woff2',
  // /manifest.webmanifest: the install icons it names
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/maskable-512.png',
  // PRECACHE_EXTRA in scripts/build-sw.js: fetched at run time, no tag names them
  '/app/',
  '/app/index.html',
  '/render-worker.js',
  '/vendor/pdf.worker.min-3.11.174.js',
  '/rules/rules.json',
];

// Per-file integrity hashes for the verified install. GENERATED by
// `npm run build:sw` — do not edit by hand (see the header comment).
const PRECACHE_SHA256 = {
  '/favicon.ico': '245190b9033ded10d89660935858c3e9fe2046e24c1c9271c9f1067eced35ad4',
  '/icons/favicon.svg': '5e4845129109e7312a2e0b538c99cad4121dec3ad210f9db6788b85faace59b5',
  '/manifest.webmanifest': '91c2a30960da9245e4472fb4b3c2ba818a505179d0c4cd58a35e53ae3c0722df',
  '/icons/apple-touch-180.png': 'a3cc9422d951a7f34950c199e4f5520eff022c706cb08915be24cb3bdd723ac6',
  '/vendor/fonts/fonts.css': '752c6612ddc928ba5144c45b23d3e6266969c760b6cac410b14ca3f2eddf4afe',
  '/config.js': '455a751857efe37a6c08d3922448bca7f57767b923e39826239a6f187608b05a',
  '/vendor/pdf.min-3.11.174.js': '5b5799e6f8c680663207ac5b42ee14eed2a406fa7af48f50c154f0c0b1566946',
  '/vendor/pdf-lib-1.17.1.min.js': '0f9a5cad07941f0826586c94e089d89b918c46e5c17cf2d5a3c6f666e3bc694f',
  '/vendor/html2canvas-1.4.1.min.js': 'e87e550794322e574a1fda0c1549a3c70dae5a93d9113417a429016838eab8cb',
  '/vendor/jspdf.umd-2.5.1.min.js': '98ccf17aa10c20bb1301762618fcc9b6ab3a4e7f26b6071d64d0b41154df3875',
  '/vendor/supabase-js-2.108.0.min.js': '005a6b7d396160fbe924316baa98adf198dc6f99a63412e27edec9675c225270',
  '/vendor/tus-js-client-4.3.1.min.js': '8cbb1b63fccc3bba0ae73ad1deb160ce046c3750851d0c3e94921ae3ef070eb8',
  '/styles.css': 'e5721f689aba8e5dbd8b6d0d5c133bf26270524fabc49b4edd3adb1669b06f48',
  '/icons.js': 'bb3c3506a859d25685287d0c1d3afb3231601754555aea403505e7ca8d68779b',
  '/icons-custom.js': 'efe6b960301031a5fb40abc2f54de18798e19f4b7b04e0eccb81b47f1e9cacad',
  '/icon-render.js': 'e4f3807d1ab13f61b3d0f33ec833455defa3b0d6795139ea2e61c94c1e1a9b47',
  '/geometry.js': '132ab8c676657d177634ddb9a29a27b554779d5a01dfa5e2d687dbaffb73f625',
  '/line-metrics.js': '79e7bdbc91c02ebd4c62be3a26ad33eb5822d11d7233d75eb67a8de72a5c2126',
  '/conductor-model.js': '2fdea89c54aefa85ff19260a1dd02a2d83a3d94477bda95be451fd309a6de01a',
  '/circuit-model.js': '19e0de705524e0390476d4f9346008ffdad190786c8b1720eb4a8dab64febc09',
  '/bid-check-model.js': 'bf457af6cff7152c0a6ba07420ee093a645fa6cd20e0b42c1adbfeb9453db733',
  '/tag-model.js': '73cd905aac6670c05139607d458a081218ebac55fa2bf230531eec4638cd064d',
  '/sheet-title-model.js': 'f4af651077942b4b14a4eec23effcbcf6099713125031270a868d3a21a2737cd',
  '/support-model.js': 'a1fba42dfd24cfc5dfd662e6dcb67bced82bb656f7589b828110f5d08088eb69',
  '/water-model.js': 'df427627c274b9cf8d54946353cb565f502b662a5e70ab35796a167e09d95260',
  '/fitting-model.js': '60aef6daecbf4ea7205224b2656d3bdaca033fa9ce9f896885f56e5618b6b9b1',
  '/duct-model.js': '516ec1ae47e20728cfe71c5930052d137f0a1208aef60baada5cafa16d6e66a7',
  '/bid-basis-model.js': '825fc0a1cfd1a765dbb3bab5f06eb49c9780253d071def87784939e194a834f0',
  '/status-hint-model.js': 'b55e1c0217607899538609aa147fe19649650d1b8cfd141469277199f576d240',
  '/canvas-draw.js': 'e247bd9f97f6d4bc8ce035506538833d18864785d7abe9398401c3d6428dc446',
  '/render-service.js': '077e7474ba588a262ca7fe01183271af85d8a9a105e4c90cb1ebd5ed7d8ab0da',
  '/constants.js': '5322207361efb23c360f498be918190ea321096e3a3a4f36c073e27564b6b92a',
  '/zoom-ladder.js': 'c8396a9b8610ce94c703b575e3180ad3152d17a5b23c9e576c8d45b980005ba3',
  '/hotkeys.js': 'cd0eafcc9f24c885d3e4e10d0a5d2e493f54be34d2e8607f53dd456f44c49d23',
  '/recent-colors.js': '01a7af7515a037ac51f0819601156c64035b903ce55a2739a5393988792285a7',
  '/recent-drops.js': '3b04d7b96c6260858a3ce9de59a9e862fa88ddf3e563de3ef46d354020358b7b',
  '/recent-bids.js': '0c27598ee2b7013f553eef5456b257935bc1de5810db43660afd4b74975a89bb',
  '/idb.js': 'ae6bf34b5675883ed82c23229597911165036a2f12e7566dbbd949b86f316f05',
  '/format.js': '8957d41b6a883fe315b79aaf6b4b34f89cc0063970394f00aa16fcbd8a0339a2',
  '/save-utils.js': '1d6b10bdad7b6377819a3e411eb330294b85de44faecf8641c037db8b6450bd8',
  '/annotation-model.js': '27abdf0ca8cef2cdb96898a8af01fb2fb5e689526792401c89ba43d1cd0989e2',
  '/undo-stack.js': '34180b25071008b6f29c8b3c2529faa29e21c2957e9ee26b5510e5ef5750f69c',
  '/save-engine.js': '282a77231451d1b68b5773673afe1985cc4e4ef02fd8bae820293141e9d128db',
  '/pdf-tile-cache.js': 'd9d520d6399480191df2b97038ce0b453803666d79f1b804a995484e98fc5772',
  '/app.js': '1311d7cb0af04e813f00774240a24f0e73756ea56c6ed6fb9a81303590242175',
  '/features/canvas-repair.js': 'b2dca5c86174ed9589d0c44091d9265c2e3af039c08cf4422eb151fa5fd8ec02',
  '/features/view-only.js': 'f4e6c4f5601c089aa1001a9583c409e61d9090a639acd6a69994bccd6ca0dbcc',
  '/features/save-project.js': '6f01819d040f4a05ee9805ccabdc5170973429a39d5d0c3e54381a0d43866ad2',
  '/features/pdf-intake.js': '03656a87a61695ddbff4ae702a57e40b4b8d00d90de222936f88ce74c4c078ac',
  '/features/line-color.js': '2fd4c7594f1a3686fd9323b7bc4d97f5b9c151b32475d5a4428062a075378ecb',
  '/features/custom-icon-upload.js': 'cf0d6731862f3baa8b7ed55cbfc89759df42934f52d1c22586ac37d3b406ab06',
  '/features/note.js': 'b7cc88aa00ac8a2450c59299959108ae3bd5b18b0e420fd61264533c23347d6b',
  '/features/zoom.js': 'cceb56f7ae4c91124aa17b246b276b9796463dc27ce93835a849f5a3d31f31fc',
  '/features/zoom-rail.js': '85680eb13fb2187af0f9716289b9befba7abef84590aad8ca78f10b9d3f60665',
  '/features/manage-icons.js': '69a7ac7533470d5b9711cc8ad0c0512bc18ac5b200b09e9942aee5042afd87dc',
  '/features/multiply-zone-settings.js': 'e808757a5758d7c0ba64d989ef3f6e051266b40a26ff01ae9ea8187b7b834dee',
  '/features/scale-zone-settings.js': '67a8a802e7aeaf629a235dbd0e4d9c42ea5c746412ae6749b90ecf35be7a9c9f',
  '/features/export-pdfs.js': '91ef0aa9fea0eba86e27dc158070cb0824647bf42e0051f35869ca1bb2854901',
  '/features/bid-basis.js': '1effb492871d0ec5fb3de46d4f9e72e25efedac4708cd9c86af1e735abbd352c',
  '/features/legend-settings.js': 'd9a749587acf289b31503bfb2bc764868f507296b272ef880938359f919a9976',
  '/features/page-settings.js': '2e9b961016930ea467a50e9a426cf8aa3a901f10dd2fb2fbe11a9186c7020e40',
  '/features/counter-settings.js': 'a36664ce5a4ed0b8097becf5809c4d13b0114bd08d9c23791555ef4acc738eab',
  '/features/line-type-settings.js': '4fb2d7d8193b2b21f314b89982286922f040942c227793d07cda3d08cdb5198f',
  '/features/choose-create-line-type.js': '58905eaa89e7bcf66fa930b9cbf3964758fcd7ff2bd3b6aa9155918137997a07',
  '/features/scale.js': '37d0a220079c2141d1d8dc65a0c9af0b9e504aa64f3fec7ada0da0f176f3878d',
  '/features/groups.js': 'a7ef74b8e7915d18ccdfcfd926e5ed2afb3fe8c042a5749a4efcbb1ed190127c',
  '/features/grid.js': 'bfe967382b165655bc9d3bb00b2465cb4e1ffd612e05c46121ce2704764cbe9a',
  '/features/quick-line.js': '8a68ae922487c3fc962fa71017f1efcf475fdc6f44ddbdb5bedcd3ed9159393a',
  '/features/counter.js': 'df961b39622beee05ccb62478904384a03ab84461ddce3788bac4c5bf5bb432b',
  '/features/save-status.js': 'd656c3245ae372bbfca907c6ca90d7367fc56e284919d625fbfe1720209fa33a',
  '/features/status-bar.js': 'c193fa3870a47b976a8d479d4f4e0128827acb6756b94fdc093527586b279e42',
  '/features/turn-in.js': 'a03e2ca2e0b21fd07b23d9eda1ac651cbeeba70c4ccdad5097ca320e08e9da62',
  '/features/manage-projects.js': '45d9d7418dd748b6a18089bb1ea9b6daa67a86ad8d3233945cb24a3a762f4a93',
  '/features/user-admin.js': 'f038517632e11bb24f6cc01254611534ead640264baa7fa6152de542791914ec',
  '/features/load-project.js': 'e20d60a871bc1497d0fe32ffca5335cf5397ff981b2d50844845a0eb2494182b',
  '/features/bid-board.js': '9b566cfd9ea3346fff1f7d0e71637cf1508a3edbda6c6630a938aa680feea8bf',
  '/features/review-flow.js': '9d474b055c8d4ba4fc7cab2a3b3e3c5eca031693c1d1870791ae3636fdd3ca6e',
  '/features/copy-project.js': '7668abd5e8121edc27c3155882da4c252791455a5a7bdd4a6accbe36ef0bea09',
  '/features/prepare-pdf.js': '1ba54d315cca56a94dcf6e81b7376557f409f2fe05a86df82b4172aa58d93914',
  '/features/quick-modals.js': '090df565d0ae18d292b388b42981c975587f9869feb78b139316377e60845f51',
  '/features/pdf-bundle.js': '9f08fe5a316ff8c82561c4655c6b2d4d4858268bb3ee2807fe6e61df0cc8351e',
  '/features/item-details.js': '5b27cce6a33a4439ef426db2b55f03b0b93413b07f03e66044bfec646711cdb1',
  '/features/output.js': '7dd63a53dd8a0bd8f6fcf975766ab713078119fcd80c3297ca923726c5209ed1',
  '/features/rfi-flags.js': '4321db07f601a5636f04d42a9e746498eb03ad1005213e2e248aad8e66fdb41b',
  '/features/notes-ledger.js': '291effbe0dcaf4fcbcbd4b8bc9e3371c5c8c8e1564d2b1a68d7db96bb03f7e92',
  '/features/share-links.js': '8988dea7364d6d7e9aeca68ef1276fea0e878e4057f2cfc22fe89f6e992220f7',
  '/features/import-clear.js': 'a60207b82190ff07ee6e0850a6264213da94de9a55b9e7fa77b6b0e90ffb8844',
  '/features/zone-modals.js': '1981de3740bb45e16edf901b9ed9d8dccbe7538f248f1c9a1ec16f271da856ab',
  '/features/restore-last-session.js': 'ee74a0fc50d46e502453c2b7b10f52df16b94573c68e9ed06690bfa0523b1de6',
  '/features/summary-detail.js': 'd47742a59b401b0f35bda3469b8f7bad7425cda14fcaf88cfb2023caea7b3892',
  '/features/room-sizer.js': '9c78abcbde1128f583fafacfdea28f613a81c4ee13c8a2c57af7c8c2caa685cf',
  '/features/burger-menu.js': 'ace047ffd97c17d329ff3d2af9853c5439fcbe33e46619b5c22881da182dbe12',
  '/features/bid-chip.js': '25850cbf620075cd0b20b79ab3910340a90fe3b4532853980653f9c2d94bf845',
  '/features/header-more.js': '5ac497cb75bf94b20da440f4dfb4996cd6a6bbde2d5c7ee3a9b00e43d976f5de',
  '/features/canvas-layers.js': '4221ddc56bcd2447eb6bd7ecdb681872753d3808c4b228c17188975758077575',
  '/features/ghost.js': '25bdc3673bdf59bde86b8684d7d431f7bcf4e8c2c31f63aa46ca83d378829f5e',
  '/features/canvas-switcher.js': '89970ea9ae56c8bffa8f3fd0360ea4ba3e901bec1a772972117dcebe5acc9393',
  '/features/summary-list.js': '56265a167565700edbea57ed56c4c8cba70c60ab0f7bf839fc463a186ff0091d',
  '/features/my-settings.js': 'd3792711b4d9107dd53770c2ec09da1c1911882d0be95de63d86715170d67efa',
  '/features/palette-insights.js': '295538e042d1cef9c0b12655b754c5b9ca26a02de010f684806c88e777085863',
  '/features/user-activity.js': '2548c3835c9870092c4e3ba6de191b1493b4a81b7739bd144d96dcf20fcb19eb',
  '/features/user-activity-overview.js': '70895b1093150ee2c4049540df9eb0a40f13af17868e482ad178dac7a7c02b10',
  '/features/tool-context-menu.js': 'b3eaa212bea057c6497afddaba467cc9ce0a03f4f922559b49b914824fbe1266',
  '/features/bend-override.js': '875ab8446dc799619494191dc2b3e62097c0d3193c64094686c82f096d7a284c',
  '/features/lines-list.js': '84517cb4fe787e74fb94b7f0c2e28bb4e9960208e8a2d838541e85329614fcc6',
  '/features/pages-list.js': 'a23c643abca9ee91fa3476a03fe8c3083e126ba76a1f5843af74889fb8766630',
  '/features/sidebar-lists.js': '1e810a2acf5e6578f964ea8e999cdbbe1db2978cabd972c6ab5aec4f21fe9512',
  '/features/quick-keys.js': '7450dcd62a16ddf552affb569c8b19ede4776e3f8348267b0fe0eb8ccd4d0b7d',
  '/features/keyboard-map.js': '88de003bb6819a8f55a7fbf81b5cd4941860e06e0eff2dc349c8be735978ac84',
  '/features/chain.js': '1f90b93a6a9b801ff262f9e77ab28afd350ce8ef94b2a54b171516b6cfe6e9d5',
  '/features/drop-mode.js': 'ddc9792a551d3cff3bdc5a557406cd9ceb93dc14c5392a8bc28e7b1c9751cade',
  '/features/duct-tool.js': '41476b890bd0c50ccb72e937efe6cae49054fd7b02a09b9124878e5cb40492ee',
  '/features/duct-size-popover.js': '55eee93f772e8b1b79f987595fdb085c29573be3d0f45b9d9608d0c27e1180d6',
  '/features/duct-fittings.js': '70f388061436fd9f7ca7677fed135004a4577425026c3751eacc040952d7f5bb',
  '/features/duct-sidebar.js': '3297ab15e10f0905ce293cdd58e18a1386f479b8fdca510d4bd580d65f26e895',
  '/features/duct-schedule.js': '960e66f97f83e48220753f4e89e77c7842f75e4332740f8a9f573c0c8b4adc9e',
  '/features/duct-suggest.js': '3844bb022cc59fd10df24bc9979351975b6313c33be569900828cd82146d1dd6',
  '/features/water-fixtures.js': 'bc7480a8869ec98efab4a9b01654cb1d43b57073522a2b83cb194780020f32c3',
  '/features/water-runs.js': '87e1ec21e43d8c3c1dbe4ac11f0743d985500911cf7eb01e2e21108fd86c404e',
  '/features/water-size.js': '9a4659ed32f17421a4b02e2566c12e8a78e79c06d5831ebbd166cf22bdb87820',
  '/features/water-schedule.js': '25b1801a2be70b4eaaedba90d9b01c2f3260ff5a4bac0c0665e4198f6292756f',
  '/features/water-bidcheck.js': '28eedef1c20e014e710c08769489e088a1bbea0bbf01803ec801777cd8274b9f',
  '/features/duct-callouts.js': '70b3eb17180c642962c33bb8867bb9339f551e8bbbcc831fdb5965597b9d459c',
  '/features/drop-peek.js': 'dcd5c8370524158cf579e747c155167e7407e7fbeaaeba4cbac7866fcf3bfb69',
  '/features/highlight-labels.js': '00d5ab84f963b1d5a03e78bcc5d133f04bd44c20c88e0847b6a6be86b9cdd0eb',
  '/features/hotkey-peek.js': '6f8453b22b2a5ee1b84d5760c00b47dc45f94a435ff59f7d9c991b88b6f30820',
  '/features/esc-ladder.js': '9c33509f24deb3d0773ffce0edb161e02ad83f728defd4d5cd8389ed1afef628',
  '/features/child-counts.js': '24a3e8c124579d2c63e18a74410a9cd26869eba89db97e780bad23fe9ea6b4fd',
  '/features/conductors.js': 'd8493c4f75981def0ef3f63a36399badfdc4e01f694aff6eb5bfaaf25c6c3dbf',
  '/features/circuits.js': '1b5fcf486faf36f2333bde65bc4c75d3ad314710fee01b8874333cebc46e13de',
  '/features/rules.js': '2c3b3db98897ff9eb380b172dfc3582c6aac6fd0fd4b8d47c3f40a0cc9bbf01c',
  '/features/bid-check.js': '71a6725a139558fe95784dad5ce1143429f228c80bb275ecf45252e9ea5d9f91',
  '/features/duct-bidcheck.js': '3b9cdc4940f7b82fccc6c2999543dc0968422166e68ad67096f1cb7de2714d39',
  '/features/tag-reader.js': 'ea0cc37ee4d8aa9dd202ea4682960e9c0ca3770f84292419e2ef6ed76b1f4a79',
  '/features/tutorial.js': 'dc98bb21d34386a19708cdaefee4230565b6414152feb2485edac100014dc76e',
  '/features/lessons.js': '64f11f292300f341ba83c05b8f031a300833ac5e3524b8f21baaca8dd7182fe7',
  '/features/course-plumbing.js': '2a5152929c41ced1e97f18215d4a343f783c3763983b691d567de4b04829a40e',
  '/features/course-electrical.js': '7d2535d7391ccb5eb41a5b0ba5d42c834ec2b57ddc621e90d86973d0c7adad19',
  '/features/course-hvac.js': 'cfc60ffbc13da9023967bea353d9afc40bbf87a96cab068f14b35db04a0a4979',
  '/features/tour-blank.js': 'edbd8801ce3a9a4b85621a6cc20a55a2c87242ebead416e1b62e2325b075388a',
  '/features/twin-badge.js': '714ef6850ba7f430ff181ec8c91795485553e9c27dae9c8ebd40ea75d63943bf',
  '/features/auth-magic-link.js': '56c0ffb89518846f1ac22c7ed458ffdc8d991e45838784e51203696689e5cdc5',
  '/report.js': '8a0f1f9c16b226e69d88270457677631886ad99a0596122837b506e6607acf18',
  '/vendor/fonts/dmmono-400-normal-latin-ext.woff2': '7f8712cbbd64135f9e74a527475a97cd8c5a49d8e0a1de7a65f8e2c30c5214d9',
  '/vendor/fonts/dmmono-400-normal-latin.woff2': 'fd7521f3531a5ccfc655b25c4f22e9871df3ec141ad79bb27fde20d0df347b6d',
  '/vendor/fonts/dmmono-500-normal-latin-ext.woff2': 'e284f2a17fc9cca89cc30f496945bd9a2903010944a9469fb357924da21b6f6c',
  '/vendor/fonts/dmmono-500-normal-latin.woff2': '0e263db52797086e763679c54f84ded8cc1249879bc27dca2bd5dd446f6d9f36',
  '/vendor/fonts/dmsans-300-normal-latin-ext.woff2': '219b02c7d8884817d3d6ad4c8771f2c000ce4c5669a67ef4e2e5617ffa25c4cc',
  '/vendor/fonts/dmsans-300-normal-latin.woff2': '468d56b6b25b05b70190b6c233d773f6f1770e8579827ce022a57f03fa8002fb',
  '/vendor/fonts/dmsans-400-normal-latin-ext.woff2': '219b02c7d8884817d3d6ad4c8771f2c000ce4c5669a67ef4e2e5617ffa25c4cc',
  '/vendor/fonts/dmsans-400-normal-latin.woff2': '468d56b6b25b05b70190b6c233d773f6f1770e8579827ce022a57f03fa8002fb',
  '/vendor/fonts/dmsans-500-normal-latin-ext.woff2': '219b02c7d8884817d3d6ad4c8771f2c000ce4c5669a67ef4e2e5617ffa25c4cc',
  '/vendor/fonts/dmsans-500-normal-latin.woff2': '468d56b6b25b05b70190b6c233d773f6f1770e8579827ce022a57f03fa8002fb',
  '/vendor/fonts/dmsans-600-normal-latin-ext.woff2': '219b02c7d8884817d3d6ad4c8771f2c000ce4c5669a67ef4e2e5617ffa25c4cc',
  '/vendor/fonts/dmsans-600-normal-latin.woff2': '468d56b6b25b05b70190b6c233d773f6f1770e8579827ce022a57f03fa8002fb',
  '/vendor/fonts/instrumentserif-400-italic-latin-ext.woff2': 'a04fc7ed18a8037149ce0bfda58076709d8e0840e136ed00abbdc196b7992443',
  '/vendor/fonts/instrumentserif-400-italic-latin.woff2': '6ee678c33f388dd7ba59700ebea635deb98821baafd817b09891f7927177f702',
  '/vendor/fonts/instrumentserif-400-normal-latin-ext.woff2': 'a8c4bd7cd7073180e740d2d83a616b5cb0845579b73207eeafeae8532e70c901',
  '/vendor/fonts/instrumentserif-400-normal-latin.woff2': '60c06664b5a95c7de6cc3e00d1f9034d78bd1e40b564016b241674449a067d4d',
  '/icons/icon-192.png': 'c807a7a2fda05dc5a74c60f16d7199bc1c617aa36948acc20e3712a412f943c2',
  '/icons/icon-512.png': '386919ae854bc73fd0c8fa39bcb8f16d2496ce0b487792ca17b0924d7a8eb137',
  '/icons/maskable-512.png': 'a5c54fa0ab699678992c5e5473721804d24257762a859f8c2183fb4049bfa164',
  '/app/': 'dc9257352a59cd8b25566ea8a6cbf052ca8bc6d2f04dc2ad7db05503b26aed26',
  '/app/index.html': 'dc9257352a59cd8b25566ea8a6cbf052ca8bc6d2f04dc2ad7db05503b26aed26',
  '/render-worker.js': '97409f02a7150a5f9b5e456769083b49dca0c7baaae0263a34e2fc7a1d23a54d',
  '/vendor/pdf.worker.min-3.11.174.js': 'feabdf309770ed24bba31a5467836cdc8cf639c705af27d52b585b041bb8527b',
  '/rules/rules.json': '61d5b285d5996196fb8d55b38181387109e1bd62686a23dbe81cd62ede25e969',
};

self.addEventListener('install', (event) => {
  event.waitUntil(precacheVerified().then(() => self.skipWaiting()));
});

// The verified replacement for cache.addAll: fetch every precache asset
// straight from the origin (cache: 'reload' — the HTTP cache could hand back a
// pre-deploy body that no longer matches the new sw.js's hashes), check its
// sha256 against PRECACHE_SHA256, and cache only verified bytes. ANY mismatch
// or failed fetch rejects the install: a mid-deploy CDN serving a mixed shell
// can no longer be captured into the version-stamped cache. Entries verified
// before the failure are already cache.put — harmless: they are byte-correct
// for THIS version, activate never runs on a failed install, and a later
// successful install re-puts everything. Browsers without crypto.subtle skip
// the check for that entry (yesterday's behavior).
async function precacheVerified() {
  const cache = await caches.open(CACHE_NAME);
  await Promise.all(PRECACHE_URLS.map(async (url) => {
    const res = await fetch(new Request(url, { cache: 'reload' }));
    if (!res || !res.ok) throw new Error('precache fetch failed (' + (res && res.status) + '): ' + url);
    const expected = PRECACHE_SHA256[url];
    if (expected && self.crypto && self.crypto.subtle) {
      const digest = await crypto.subtle.digest('SHA-256', await res.clone().arrayBuffer());
      const hex = Array.from(new Uint8Array(digest), (b) => b.toString(16).padStart(2, '0')).join('');
      if (hex !== expected) throw new Error('precache hash mismatch (mid-deploy CDN?): ' + url);
    }
    await cache.put(url, res);
  }));
}

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(
        keys.filter((k) => k.startsWith('counttooling-shell-') && k !== CACHE_NAME)
          .map((k) => caches.delete(k))
      ))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  // Non-GET (Supabase writes, TUS PATCH/POST, etc.) → straight to network.
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  // Cross-origin (Supabase REST/auth/realtime/storage range-requests/functions, etc.) → network.
  if (url.origin !== self.location.origin) return;

  // config.local.js is intentionally outside the precache (gitignored,
  // localhost-only) — never runtime-cache it either, or a dev's credential
  // edits get pinned to the first version cacheFirst ever saw.
  if (url.pathname === '/config.local.js') return;

  const isHtml = req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html');
  event.respondWith(isHtml ? networkFirst(req) : cacheFirst(req));
});

// Network-first for the entry document: always boot the freshest shell online, fall back
// to the precached HTML offline.
async function networkFirst(req) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const fresh = await withTimeout(fetch(req), 4000);
    if (fresh && fresh.ok) { cache.put(req, fresh.clone()).catch(() => {}); return fresh; }
    if (fresh) return fresh;
    throw new Error('no-response');
  } catch {
    return (await cache.match(req))
      || (await cache.match('/app/index.html'))
      || (await cache.match('/app/'))
      || new Response('Offline', { status: 503, statusText: 'Offline' });
  }
}

// Cache-first against the version-stamped precache: guarantees a coherent shell version
// offline; only hits the network for a precache miss.
async function cacheFirst(req) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(req);
  if (cached) return cached;
  try {
    const fresh = await fetch(req);
    if (fresh && fresh.ok && fresh.type === 'basic') cache.put(req, fresh.clone()).catch(() => {});
    return fresh;
  } catch {
    return new Response('', { status: 504, statusText: 'Offline' });
  }
}

function withTimeout(promise, ms) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('timeout')), ms);
    promise.then(
      (v) => { clearTimeout(timer); resolve(v); },
      (e) => { clearTimeout(timer); reject(e); }
    );
  });
}
