#!/usr/bin/env node
/*
 * build-macros.js — generate the Macros (Keyboard Shortcuts) table rows in
 * app/index.html from the HOTKEYS table in constants.js, the same
 * committed-artifact pattern as build-toc / build-sw / build-filemap.
 *
 * WHY: the keydown handler, the shortcut list, and the Keyboard Map were three
 * hand-maintained surfaces that drifted (the V/Room-Sizer key was live for
 * weeks with no Macros row). Now the handler EXECUTES constants.js HOTKEYS,
 * this script RENDERS it, and the Keyboard Map derives from the rendered table
 * — one source, three surfaces.
 *
 * Row icons with { btn: id } are extracted LIVE from that element's SVG in
 * app/index.html (the build-guides trick), so a row's icon always matches the
 * actual toolbar. A missing element or SVG is a HARD error — better a build
 * failure than a silently iconless row.
 *
 * Usage: node scripts/build-macros.js          (rewrite in place)
 *        node scripts/build-macros.js --check  (exit 1 if stale)
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { extractAppIcon } = require('./lib/app-icons');
const { spliceMarkedRegion, assertNoConflictMarkers } = require('./lib/markers');

const ROOT = path.join(__dirname, '..');
const APP_HTML = path.join(ROOT, 'app', 'index.html');
// Guard before require(): a conflicted hotkeys.js would otherwise die as a
// bare SyntaxError instead of the resolve-your-merge message.
assertNoConflictMarkers(fs.readFileSync(path.join(ROOT, 'hotkeys.js'), 'utf8'), 'hotkeys.js');
const { HOTKEYS } = require(path.join(ROOT, 'hotkeys.js'));

const BEGIN = '<!-- BEGIN MACROS TABLE (generated by scripts/build-macros.js — edit HOTKEYS in constants.js instead) -->';
const END = '<!-- END MACROS TABLE -->';

function extractIcon(html, id) {
  const ic = extractAppIcon(html, id);
  if (!ic) throw new Error(`icon source #${id} not found in app/index.html`);
  if (!ic.svg) throw new Error(`icon source #${id} has no <svg>`);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${ic.svg.viewBox}" width="18" height="18" class="macros-icon">${ic.svg.inner}</svg>`;
}

function iconCell(html, icon) {
  if (!icon) return '<td class="macros-icon-cell"></td>';
  if (icon.glyph) return `<td class="macros-icon-cell"><span class="macros-icon" style="font-size:1.1rem;">${icon.glyph}</span></td>`;
  return `<td class="macros-icon-cell">${extractIcon(html, icon.btn)}</td>`;
}

function kbdCell(entry) {
  const kbd = entry.kbd != null ? entry.kbd : `<kbd>${String(entry.key).toUpperCase()}</kbd>`;
  return `<td>${kbd}</td>`;
}

function rebuild(src) {
  const indent = '          ';
  const lines = [];
  let section = null;
  for (const h of HOTKEYS) {
    if (h.section !== section) {
      section = h.section;
      lines.push(`${indent}<tr><td colspan="3" class="macros-section-header">${section}</td></tr>`);
    }
    lines.push(`${indent}<tr>${iconCell(src, h.icon)}${kbdCell(h)}<td>${h.action}</td></tr>`);
  }
  const block = BEGIN + '\n' + lines.join('\n') + '\n' + indent + END;
  const out = spliceMarkedRegion(src, BEGIN, END, block);
  if (out === null) throw new Error('MACROS TABLE markers not found in app/index.html');
  return { out, changed: out !== src };
}

const src = fs.readFileSync(APP_HTML, 'utf8');
assertNoConflictMarkers(src, 'app/index.html');
const { out, changed } = rebuild(src);
const check = process.argv.includes('--check');

if (check) {
  if (changed) {
    console.error('Macros table is stale. Run `npm run build:macros` (then `npm run build:sw`) and commit.');
    process.exit(1);
  }
  console.log('Macros table up to date.');
} else if (changed) {
  fs.writeFileSync(APP_HTML, out);
  console.log(`Wrote ${HOTKEYS.length} shortcut rows into the app/index.html Macros table.`);
} else {
  console.log('Macros table already up to date.');
}
