#!/usr/bin/env node
/**
 * Regenerates the line-numbered section index in ARCHITECTURE.md from the
 * `// SECTION:` markers in index.html. The generated list is written between
 * the BEGIN/END SECTION TOC marker comments; everything else is left intact.
 *
 * Usage:
 *   node scripts/build-toc.js          rewrite the TOC block in place
 *   node scripts/build-toc.js --check  exit non-zero if the TOC is stale (CI)
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'index.html');
const DOC = path.join(ROOT, 'ARCHITECTURE.md');
const BEGIN = '<!-- BEGIN SECTION TOC (generated by scripts/build-toc.js - do not edit by hand) -->';
const END = '<!-- END SECTION TOC -->';

function buildToc(sourceText) {
  const lines = sourceText.split('\n');
  const re = /^(\s*)\/\/ SECTION:\s*(.+?)\s*$/;
  const out = [];
  lines.forEach((line, i) => {
    const m = line.match(re);
    if (!m) return;
    const indent = m[1].length > 2 ? '  ' : ''; // sub-section markers are indented deeper than the IIFE body
    const title = m[2];
    out.push(`${indent}- L${i + 1} - ${title}`);
  });
  return out.join('\n');
}

function buildBlock(toc) {
  return `${BEGIN}\n\n${toc}\n\n${END}`;
}

function main() {
  const check = process.argv.slice(2).includes('--check');

  const sourceText = fs.readFileSync(SOURCE, 'utf8');
  const docText = fs.readFileSync(DOC, 'utf8');

  const beginIdx = docText.indexOf(BEGIN);
  const endIdx = docText.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    console.error(`Could not find BEGIN/END SECTION TOC markers in ${path.relative(ROOT, DOC)}.`);
    console.error('Add these two lines where the generated index should live:');
    console.error(`  ${BEGIN}`);
    console.error(`  ${END}`);
    process.exit(1);
  }

  const toc = buildToc(sourceText);
  const updated = docText.slice(0, beginIdx) + buildBlock(toc) + docText.slice(endIdx + END.length);

  if (updated === docText) {
    console.log('Section TOC already up to date.');
    return;
  }

  if (check) {
    console.error('Section TOC is stale. Run `npm run build:toc` and commit the result.');
    process.exit(1);
  }

  fs.writeFileSync(DOC, updated, 'utf8');
  const count = toc ? toc.split('\n').length : 0;
  console.log(`Wrote ${count} section entries to ${path.relative(ROOT, DOC)}.`);
}

main();
