#!/usr/bin/env node
/**
 * Generates config.js from environment variables for CI/testing.
 * Run before cloud tests when SUPABASE_URL and SUPABASE_ANON_KEY are set.
 * Optional: DEV_AUTH_EMAIL and DEV_AUTH_PASSWORD for dev auth bypass.
 */
const fs = require('fs');
const path = require('path');

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || '';
const DEV_AUTH_EMAIL = process.env.DEV_AUTH_EMAIL || '';
const DEV_AUTH_PASSWORD = process.env.DEV_AUTH_PASSWORD || '';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.log('Skipping config generation: SUPABASE_URL and SUPABASE_ANON_KEY required');
  process.exit(0);
}

const lines = [
  '// Generated by scripts/generate-config.js - do not commit',
  'window.SUPABASE_URL = ' + JSON.stringify(SUPABASE_URL) + ';',
  'window.SUPABASE_ANON_KEY = ' + JSON.stringify(SUPABASE_ANON_KEY) + ';',
];

if (DEV_AUTH_EMAIL && DEV_AUTH_PASSWORD) {
  lines.push('window.DEV_AUTH_EMAIL = ' + JSON.stringify(DEV_AUTH_EMAIL) + ';');
  lines.push('window.DEV_AUTH_PASSWORD = ' + JSON.stringify(DEV_AUTH_PASSWORD) + ';');
}

const outPath = path.join(__dirname, '..', 'config.js');
fs.writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');
console.log('Wrote config.js from env vars');
